# -*- coding: utf-8 -*-

################################################################################
## Form generated from reading UI file 'waifu2x.ui'
##
## Created by: Qt User Interface Compiler version 6.2.2
##
## WARNING! All changes made in this file will be lost when recompiling UI file!
################################################################################

from PySide6.QtCore import (QCoreApplication, QDate, QDateTime, QLocale,
    QMetaObject, QObject, QPoint, QRect,
    QSize, QTime, QUrl, Qt)
from PySide6.QtGui import (QBrush, QColor, QConicalGradient, QCursor,
    QFont, QFontDatabase, QGradient, QIcon,
    QImage, QKeySequence, QLinearGradient, QPainter,
    QPalette, QPixmap, QRadialGradient, QTransform)
from PySide6.QtWidgets import (QApplication, QCheckBox, QGroupBox, QLabel,
    QLineEdit, QMainWindow, QPushButton, QRadioButton,
    QSizePolicy, QSlider, QStatusBar, QToolButton,
    QWidget)

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        if not MainWindow.objectName():
            MainWindow.setObjectName(u"MainWindow")
        MainWindow.resize(673, 562)
        self.centralwidget = QWidget(MainWindow)
        self.centralwidget.setObjectName(u"centralwidget")
        self.Files = QGroupBox(self.centralwidget)
        self.Files.setObjectName(u"Files")
        self.Files.setGeometry(QRect(20, 130, 631, 81))
        self.OutputPath = QLabel(self.Files)
        self.OutputPath.setObjectName(u"OutputPath")
        self.OutputPath.setGeometry(QRect(20, 50, 71, 16))
        self.InputEdit = QLineEdit(self.Files)
        self.InputEdit.setObjectName(u"InputEdit")
        self.InputEdit.setGeometry(QRect(110, 20, 451, 20))
        self.OutputEdit = QLineEdit(self.Files)
        self.OutputEdit.setObjectName(u"OutputEdit")
        self.OutputEdit.setGeometry(QRect(110, 50, 451, 20))
        self.InputPath = QLabel(self.Files)
        self.InputPath.setObjectName(u"InputPath")
        self.InputPath.setGeometry(QRect(20, 20, 71, 16))
        self.InputButton = QToolButton(self.Files)
        self.InputButton.setObjectName(u"InputButton")
        self.InputButton.setGeometry(QRect(570, 20, 41, 21))
        self.OutputButton = QToolButton(self.Files)
        self.OutputButton.setObjectName(u"OutputButton")
        self.OutputButton.setGeometry(QRect(570, 50, 41, 21))
        self.Configs = QGroupBox(self.centralwidget)
        self.Configs.setObjectName(u"Configs")
        self.Configs.setGeometry(QRect(20, 220, 631, 251))
        self.ModelSRCNN = QRadioButton(self.Configs)
        self.ModelSRCNN.setObjectName(u"ModelSRCNN")
        self.ModelSRCNN.setGeometry(QRect(150, 20, 89, 16))
        self.Model = QLabel(self.Configs)
        self.Model.setObjectName(u"Model")
        self.Model.setGeometry(QRect(20, 20, 121, 16))
        self.ModelRealESRGAN = QRadioButton(self.Configs)
        self.ModelRealESRGAN.setObjectName(u"ModelRealESRGAN")
        self.ModelRealESRGAN.setGeometry(QRect(270, 20, 131, 16))
        self.ModelRealESRGAN.setChecked(True)
        self.SRCNN = QGroupBox(self.Configs)
        self.SRCNN.setObjectName(u"SRCNN")
        self.SRCNN.setGeometry(QRect(10, 50, 321, 91))
        self.SRCNNphoto = QRadioButton(self.SRCNN)
        self.SRCNNphoto.setObjectName(u"SRCNNphoto")
        self.SRCNNphoto.setGeometry(QRect(20, 60, 261, 16))
        self.SRCNNcunet = QRadioButton(self.SRCNN)
        self.SRCNNcunet.setObjectName(u"SRCNNcunet")
        self.SRCNNcunet.setGeometry(QRect(20, 20, 261, 16))
        self.SRCNNcunet.setChecked(True)
        self.SRCNNanime = QRadioButton(self.SRCNN)
        self.SRCNNanime.setObjectName(u"SRCNNanime")
        self.SRCNNanime.setGeometry(QRect(20, 40, 301, 16))
        self.RealESRGAN = QGroupBox(self.Configs)
        self.RealESRGAN.setObjectName(u"RealESRGAN")
        self.RealESRGAN.setGeometry(QRect(10, 150, 321, 91))
        self.realesrnetx4plus = QRadioButton(self.RealESRGAN)
        self.realesrnetx4plus.setObjectName(u"realesrnetx4plus")
        self.realesrnetx4plus.setGeometry(QRect(20, 40, 261, 16))
        self.realesrganx4plusanime = QRadioButton(self.RealESRGAN)
        self.realesrganx4plusanime.setObjectName(u"realesrganx4plusanime")
        self.realesrganx4plusanime.setGeometry(QRect(20, 60, 311, 16))
        self.realesrganx4plus = QRadioButton(self.RealESRGAN)
        self.realesrganx4plus.setObjectName(u"realesrganx4plus")
        self.realesrganx4plus.setGeometry(QRect(20, 20, 261, 16))
        self.realesrganx4plus.setChecked(True)
        self.Denoise = QGroupBox(self.Configs)
        self.Denoise.setObjectName(u"Denoise")
        self.Denoise.setGeometry(QRect(350, 50, 271, 91))
        self.DenoiseSlider = QSlider(self.Denoise)
        self.DenoiseSlider.setObjectName(u"DenoiseSlider")
        self.DenoiseSlider.setGeometry(QRect(60, 40, 160, 22))
        self.DenoiseSlider.setMinimum(-1)
        self.DenoiseSlider.setMaximum(3)
        self.DenoiseSlider.setOrientation(Qt.Horizontal)
        self.DenoiseSlider.setTickPosition(QSlider.TicksBelow)
        self.DenoiseSlider.setTickInterval(1)
        self.Denoise0 = QLabel(self.Denoise)
        self.Denoise0.setObjectName(u"Denoise0")
        self.Denoise0.setGeometry(QRect(60, 70, 54, 12))
        self.Denoise3 = QLabel(self.Denoise)
        self.Denoise3.setObjectName(u"Denoise3")
        self.Denoise3.setGeometry(QRect(180, 70, 54, 12))
        self.Denoise4 = QLabel(self.Denoise)
        self.Denoise4.setObjectName(u"Denoise4")
        self.Denoise4.setGeometry(QRect(210, 70, 54, 12))
        self.Denoise1 = QLabel(self.Denoise)
        self.Denoise1.setObjectName(u"Denoise1")
        self.Denoise1.setGeometry(QRect(100, 70, 54, 12))
        self.Denoise2 = QLabel(self.Denoise)
        self.Denoise2.setObjectName(u"Denoise2")
        self.Denoise2.setGeometry(QRect(140, 70, 54, 12))
        self.Denoiselabel = QLabel(self.Denoise)
        self.Denoiselabel.setObjectName(u"Denoiselabel")
        self.Denoiselabel.setGeometry(QRect(60, 20, 211, 16))
        self.Scale = QGroupBox(self.Configs)
        self.Scale.setObjectName(u"Scale")
        self.Scale.setGeometry(QRect(350, 150, 271, 91))
        self.ScaleSlider = QSlider(self.Scale)
        self.ScaleSlider.setObjectName(u"ScaleSlider")
        self.ScaleSlider.setGeometry(QRect(60, 40, 160, 22))
        self.ScaleSlider.setMinimum(0)
        self.ScaleSlider.setMaximum(5)
        self.ScaleSlider.setPageStep(1)
        self.ScaleSlider.setValue(2)
        self.ScaleSlider.setOrientation(Qt.Horizontal)
        self.ScaleSlider.setTickPosition(QSlider.TicksBelow)
        self.Scale3 = QLabel(self.Scale)
        self.Scale3.setObjectName(u"Scale3")
        self.Scale3.setGeometry(QRect(120, 70, 54, 12))
        self.Scale2 = QLabel(self.Scale)
        self.Scale2.setObjectName(u"Scale2")
        self.Scale2.setGeometry(QRect(90, 70, 54, 12))
        self.Scale6 = QLabel(self.Scale)
        self.Scale6.setObjectName(u"Scale6")
        self.Scale6.setGeometry(QRect(210, 70, 54, 12))
        self.Scale1 = QLabel(self.Scale)
        self.Scale1.setObjectName(u"Scale1")
        self.Scale1.setGeometry(QRect(60, 70, 54, 12))
        self.Scale4 = QLabel(self.Scale)
        self.Scale4.setObjectName(u"Scale4")
        self.Scale4.setGeometry(QRect(150, 70, 54, 12))
        self.Scale5 = QLabel(self.Scale)
        self.Scale5.setObjectName(u"Scale5")
        self.Scale5.setGeometry(QRect(180, 70, 54, 12))
        self.Scalelabel = QLabel(self.Scale)
        self.Scalelabel.setObjectName(u"Scalelabel")
        self.Scalelabel.setGeometry(QRect(60, 20, 161, 16))
        self.Introduction = QGroupBox(self.centralwidget)
        self.Introduction.setObjectName(u"Introduction")
        self.Introduction.setGeometry(QRect(20, 10, 631, 111))
        self.description = QLabel(self.Introduction)
        self.description.setObjectName(u"description")
        self.description.setGeometry(QRect(20, 10, 601, 91))
        self.description.setTextFormat(Qt.AutoText)
        self.description.setScaledContents(False)
        self.description.setWordWrap(True)
        self.description.setOpenExternalLinks(True)
        self.Actions = QGroupBox(self.centralwidget)
        self.Actions.setObjectName(u"Actions")
        self.Actions.setGeometry(QRect(20, 480, 631, 51))
        self.Generate = QPushButton(self.Actions)
        self.Generate.setObjectName(u"Generate")
        self.Generate.setGeometry(QRect(320, 20, 75, 23))
        self.Cancel = QPushButton(self.Actions)
        self.Cancel.setObjectName(u"Cancel")
        self.Cancel.setGeometry(QRect(420, 20, 75, 23))
        self.OpenImage = QCheckBox(self.Actions)
        self.OpenImage.setObjectName(u"OpenImage")
        self.OpenImage.setGeometry(QRect(20, 20, 251, 16))
        self.OpenImage.setChecked(True)
        self.About = QPushButton(self.Actions)
        self.About.setObjectName(u"About")
        self.About.setGeometry(QRect(520, 20, 75, 23))
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QStatusBar(MainWindow)
        self.statusbar.setObjectName(u"statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)

        QMetaObject.connectSlotsByName(MainWindow)
    # setupUi

#     def retranslateUi(self, MainWindow):
#         MainWindow.setWindowTitle(QCoreApplication.translate("MainWindow", u"Waifu2x - AI-powered Image Resize Tool", None))
#         self.Files.setTitle(QCoreApplication.translate("MainWindow", u"Files", None))
#         self.OutputPath.setText(QCoreApplication.translate("MainWindow", u"Output Folder", None))
#         self.OutputEdit.setText("")
#         self.InputPath.setText(QCoreApplication.translate("MainWindow", u"Input Path(s)", None))
#         self.InputButton.setText(QCoreApplication.translate("MainWindow", u"...", None))
#         self.OutputButton.setText(QCoreApplication.translate("MainWindow", u"...", None))
#         self.Configs.setTitle(QCoreApplication.translate("MainWindow", u"Configs", None))
#         self.ModelSRCNN.setText(QCoreApplication.translate("MainWindow", u"SRCNN(2015)", None))
#         self.Model.setText(QCoreApplication.translate("MainWindow", u"Processing Engine", None))
#         self.ModelRealESRGAN.setText(QCoreApplication.translate("MainWindow", u"Real-ESRGAN(2021)", None))
#         self.SRCNN.setTitle(QCoreApplication.translate("MainWindow", u"SRCNN Type", None))
#         self.SRCNNphoto.setText(QCoreApplication.translate("MainWindow", u"upconv_7_photo(better for photo)", None))
#         self.SRCNNcunet.setText(QCoreApplication.translate("MainWindow", u"cunet(default)", None))
#         self.SRCNNanime.setText(QCoreApplication.translate("MainWindow", u"upconv_7_anime_style_art_rgb(better for anime)", None))
#         self.RealESRGAN.setTitle(QCoreApplication.translate("MainWindow", u"Real-ESRGAN Type", None))
#         self.realesrnetx4plus.setText(QCoreApplication.translate("MainWindow", u"realesrnet-x4plus(alternative)", None))
#         self.realesrganx4plusanime.setText(QCoreApplication.translate("MainWindow", u"realesrgan-x4plus-anime(optimized for anime)", None))
#         self.realesrganx4plus.setText(QCoreApplication.translate("MainWindow", u"realesrgan-x4plus(default)", None))
#         self.Denoise.setTitle(QCoreApplication.translate("MainWindow", u"Denoise(SRCNN)", None))
#         self.Denoise0.setText(QCoreApplication.translate("MainWindow", u"-1", None))
#         self.Denoise3.setText(QCoreApplication.translate("MainWindow", u"2", None))
#         self.Denoise4.setText(QCoreApplication.translate("MainWindow", u"3", None))
#         self.Denoise1.setText(QCoreApplication.translate("MainWindow", u"0", None))
#         self.Denoise2.setText(QCoreApplication.translate("MainWindow", u"1", None))
#         self.Denoiselabel.setText(QCoreApplication.translate("MainWindow", u"Select the smooth factor.", None))
#         self.Scale.setTitle(QCoreApplication.translate("MainWindow", u"Scale(SRCNN)", None))
#         self.Scale3.setText(QCoreApplication.translate("MainWindow", u"4", None))
#         self.Scale2.setText(QCoreApplication.translate("MainWindow", u"2", None))
#         self.Scale6.setText(QCoreApplication.translate("MainWindow", u"32", None))
#         self.Scale1.setText(QCoreApplication.translate("MainWindow", u"1", None))
#         self.Scale4.setText(QCoreApplication.translate("MainWindow", u"8", None))
#         self.Scale5.setText(QCoreApplication.translate("MainWindow", u"16", None))
#         self.Scalelabel.setText(QCoreApplication.translate("MainWindow", u"Select the scale ratio.", None))
#         self.Introduction.setTitle(QCoreApplication.translate("MainWindow", u"Introduction", None))
#         self.description.setText(QCoreApplication.translate("MainWindow", u"This tool allows you to magnify your image with smoothing, especially for anime screenshots and illustrations.\n"
# "(1) Set your input path and output path in Files Panel. Please use same file extensions for input and output.\n"
# "(2) Select your preferred engine and parameters in Configs Panel. (staying default is recommended) \n"
# "(3) Click Generate in Action Panel and wait for several minutes to process. ", None))
#         self.Actions.setTitle(QCoreApplication.translate("MainWindow", u"Actions", None))
#         self.Generate.setText(QCoreApplication.translate("MainWindow", u"Generate", None))
#         self.Cancel.setText(QCoreApplication.translate("MainWindow", u"Cancel", None))
#         self.OpenImage.setText(QCoreApplication.translate("MainWindow", u"Open Output Folder After Generation", None))
#         self.About.setText(QCoreApplication.translate("MainWindow", u"About", None))
    # retranslateUi

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(QCoreApplication.translate("MainWindow", u"Waifu2x - 人工智能图像放大工具", None))
        self.Files.setTitle(QCoreApplication.translate("MainWindow", u"文件", None))
        self.OutputPath.setText(QCoreApplication.translate("MainWindow", u"输出文件夹", None))
        self.OutputEdit.setText("")
        self.InputPath.setText(QCoreApplication.translate("MainWindow", u"输入文件", None))
        self.InputButton.setText(QCoreApplication.translate("MainWindow", u"...", None))
        self.OutputButton.setText(QCoreApplication.translate("MainWindow", u"...", None))
        self.Configs.setTitle(QCoreApplication.translate("MainWindow", u"设置", None))
        self.ModelSRCNN.setText(QCoreApplication.translate("MainWindow", u"SRCNN(2015)", None))
        self.Model.setText(QCoreApplication.translate("MainWindow", u"处理引擎", None))
        self.ModelRealESRGAN.setText(QCoreApplication.translate("MainWindow", u"Real-ESRGAN(2021)", None))
        self.SRCNN.setTitle(QCoreApplication.translate("MainWindow", u"SRCNN 模型", None))
        self.SRCNNphoto.setText(QCoreApplication.translate("MainWindow", u"upconv_7_photo(适用照片)", None))
        self.SRCNNcunet.setText(QCoreApplication.translate("MainWindow", u"cunet(默认)", None))
        self.SRCNNanime.setText(QCoreApplication.translate("MainWindow", u"upconv_7_anime_style_art_rgb(适用动漫)", None))
        self.RealESRGAN.setTitle(QCoreApplication.translate("MainWindow", u"Real-ESRGAN 模型", None))
        self.realesrnetx4plus.setText(QCoreApplication.translate("MainWindow", u"realesrnet-x4plus(替代)", None))
        self.realesrganx4plusanime.setText(QCoreApplication.translate("MainWindow", u"realesrgan-x4plus-anime(适用动漫)", None))
        self.realesrganx4plus.setText(QCoreApplication.translate("MainWindow", u"realesrgan-x4plus(默认)", None))
        self.Denoise.setTitle(QCoreApplication.translate("MainWindow", u"去噪(SRCNN)", None))
        self.Denoise0.setText(QCoreApplication.translate("MainWindow", u"-1", None))
        self.Denoise3.setText(QCoreApplication.translate("MainWindow", u"2", None))
        self.Denoise4.setText(QCoreApplication.translate("MainWindow", u"3", None))
        self.Denoise1.setText(QCoreApplication.translate("MainWindow", u"0", None))
        self.Denoise2.setText(QCoreApplication.translate("MainWindow", u"1", None))
        self.Denoiselabel.setText(QCoreApplication.translate("MainWindow", u"选择平滑程度。", None))
        self.Scale.setTitle(QCoreApplication.translate("MainWindow", u"尺寸(SRCNN)", None))
        self.Scale3.setText(QCoreApplication.translate("MainWindow", u"4", None))
        self.Scale2.setText(QCoreApplication.translate("MainWindow", u"2", None))
        self.Scale6.setText(QCoreApplication.translate("MainWindow", u"32", None))
        self.Scale1.setText(QCoreApplication.translate("MainWindow", u"1", None))
        self.Scale4.setText(QCoreApplication.translate("MainWindow", u"8", None))
        self.Scale5.setText(QCoreApplication.translate("MainWindow", u"16", None))
        self.Scalelabel.setText(QCoreApplication.translate("MainWindow", u"选择放大倍率。", None))
        self.Introduction.setTitle(QCoreApplication.translate("MainWindow", u"介绍", None))
        self.description.setText(QCoreApplication.translate("MainWindow", u"此工具可让您通过平滑放大图像，尤其是对于动漫屏幕截图和插图。\n"
"(1) 在文件面板中设置输入路径和输出路径。 请使用相同的文件扩展名进行输入和输出。\n"
"(2) 在配置面板中选择您喜欢的引擎和参数。 （建议保持默认） \n"
"(3) 单击操作面板中的生成并等待几分钟进行处理。 ", None))
        self.Actions.setTitle(QCoreApplication.translate("MainWindow", u"操作", None))
        self.Generate.setText(QCoreApplication.translate("MainWindow", u"生成", None))
        self.Cancel.setText(QCoreApplication.translate("MainWindow", u"取消", None))
        self.OpenImage.setText(QCoreApplication.translate("MainWindow", u"生成后打开文件夹", None))
        self.About.setText(QCoreApplication.translate("MainWindow", u"关于", None))
